// Auto-generated by @cerios/openapi-to-zod
// Do not edit this file manually

// Generation Statistics:
//   Total schemas: 3
//   Enums: 0
//   Circular references: 0
//   Discriminated unions: 0
//   With constraints: 0
//   Generated at: 2025-12-08T19:37:45.591Z

import { z } from "zod";

// Schemas and Types
/** A user in the system */
export const userSchema = z.object({
	/** The unique identifier for the user */
	id: z.uuid(),
	/** The user's full name */
	name: z.string(),
	/** The user's email address */
	email: z.email().optional(),
	/** The user's age in years */
	age: z.number().int().optional(),
	/** Whether the user account is active */
	isActive: z.boolean().optional(),
});
export type User = z.infer<typeof userSchema>;

export const statusSchema = z.enum(["active", "inactive", "pending"]);
export type Status = z.infer<typeof statusSchema>;

export const addressSchema = z.object({
	street: z.string().optional(),
	city: z.string().optional(),
	postalCode: z.string().optional(),
});
export type Address = z.infer<typeof addressSchema>;
