import { describe, expect, it } from "vitest";

import { generateCustomFileHeader, generateFileHeader } from "../src/utils/header-utils";

describe("header-utils", () => {
	describe("generateFileHeader", () => {
		it("should generate header with package name only", () => {
			const result = generateFileHeader({ packageName: "@cerios/openapi-to-zod" });

			expect(result).toBe("// Auto-generated by @cerios/openapi-to-zod\n// Do not edit this file manually\n\n");
		});

		it("should include API title when provided", () => {
			const result = generateFileHeader({
				packageName: "@cerios/openapi-to-k6",
				apiTitle: "Pet Store API",
			});

			expect(result).toBe(
				"// Auto-generated by @cerios/openapi-to-k6\n// API: Pet Store API\n// Do not edit this file manually\n\n"
			);
		});

		it("should include API version when provided", () => {
			const result = generateFileHeader({
				packageName: "@cerios/openapi-to-typescript",
				apiVersion: "1.2.3",
			});

			expect(result).toBe(
				"// Auto-generated by @cerios/openapi-to-typescript\n// Version: 1.2.3\n// Do not edit this file manually\n\n"
			);
		});

		it("should include both API title and version when provided", () => {
			const result = generateFileHeader({
				packageName: "@cerios/openapi-to-k6",
				apiTitle: "Pet Store API",
				apiVersion: "2.0.0",
			});

			expect(result).toBe(
				"// Auto-generated by @cerios/openapi-to-k6\n// API: Pet Store API\n// Version: 2.0.0\n// Do not edit this file manually\n\n"
			);
		});

		it("should omit do not edit line when includeDoNotEdit is false", () => {
			const result = generateFileHeader({
				packageName: "@cerios/openapi-to-zod",
				includeDoNotEdit: false,
			});

			expect(result).toBe("// Auto-generated by @cerios/openapi-to-zod\n\n");
		});

		it("should omit do not edit line but keep API info when includeDoNotEdit is false", () => {
			const result = generateFileHeader({
				packageName: "@cerios/openapi-to-zod-playwright",
				apiTitle: "My API",
				apiVersion: "3.0.0",
				includeDoNotEdit: false,
			});

			expect(result).toBe(
				"// Auto-generated by @cerios/openapi-to-zod-playwright\n// API: My API\n// Version: 3.0.0\n\n"
			);
		});

		it("should return string with double trailing newline", () => {
			const result = generateFileHeader({ packageName: "@cerios/openapi-to-zod" });

			expect(result.endsWith("\n\n")).toBe(true);
		});
	});

	describe("generateCustomFileHeader", () => {
		it("should return empty string for undefined input", () => {
			const result = generateCustomFileHeader(undefined);

			expect(result).toBe("");
		});

		it("should return empty string for empty array", () => {
			const result = generateCustomFileHeader([]);

			expect(result).toBe("");
		});

		it("should generate header from single line", () => {
			const result = generateCustomFileHeader(["// oxlint-disable"]);

			expect(result).toBe("// oxlint-disable\n\n");
		});

		it("should generate header from multiple lines", () => {
			const result = generateCustomFileHeader([
				"// oxlint-disable typescript/no-unsafe-type-assertion",
				"// oxlint-disable typescript/no-unsafe-assignment",
			]);

			expect(result).toBe(
				"// oxlint-disable typescript/no-unsafe-type-assertion\n// oxlint-disable typescript/no-unsafe-assignment\n\n"
			);
		});

		it("should preserve any string format (not just comments)", () => {
			const result = generateCustomFileHeader(["/* eslint-disable */", "// @ts-nocheck", "'use strict';"]);

			expect(result).toBe("/* eslint-disable */\n// @ts-nocheck\n'use strict';\n\n");
		});

		it("should end with double newline", () => {
			const result = generateCustomFileHeader(["// test"]);

			expect(result.endsWith("\n\n")).toBe(true);
		});
	});
});
