import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { OpenApiK6Generator } from "../src/openapi-k6-generator";
import type { K6ConfigFile } from "../src/types";
import { mergeConfigWithDefaults } from "../src/utils/config-loader";

describe("fileHeader option", () => {
	const fixtureFile = resolve(__dirname, "fixtures/simple-api.yaml");

	describe("generator output", () => {
		it("should include custom header at the very top of client output", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
				fileHeader: ["// oxlint-disable typescript/no-unsafe-type-assertion"],
			});

			const output = generator.generateString();

			// Should start with custom header
			expect(output.startsWith("// oxlint-disable typescript/no-unsafe-type-assertion")).toBe(true);

			// Should still have auto-generated comment after
			expect(output).toContain("// Auto-generated by @cerios/openapi-to-k6");
		});

		it("should include multiple custom header lines at very top", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
				fileHeader: [
					"// oxlint-disable typescript/no-unsafe-type-assertion",
					"// oxlint-disable typescript/no-unsafe-assignment",
				],
			});

			const output = generator.generateString();
			const lines = output.split("\n");

			// First two lines should be our custom headers
			expect(lines[0]).toBe("// oxlint-disable typescript/no-unsafe-type-assertion");
			expect(lines[1]).toBe("// oxlint-disable typescript/no-unsafe-assignment");

			// Should have blank line after custom headers
			expect(lines[2]).toBe("");

			// Should still have auto-generated comment
			expect(output).toContain("// Auto-generated by @cerios/openapi-to-k6");
		});

		it("should not include custom header when fileHeader is empty array", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
				fileHeader: [],
			});

			const output = generator.generateString();

			// Should start with auto-generated comment
			expect(output.startsWith("// Auto-generated by @cerios/openapi-to-k6")).toBe(true);
		});

		it("should not include custom header when not specified", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
			});

			const output = generator.generateString();

			// Should start with auto-generated comment
			expect(output.startsWith("// Auto-generated by @cerios/openapi-to-k6")).toBe(true);
		});

		it("should preserve non-comment strings in fileHeader", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
				fileHeader: ["/* eslint-disable */", "'use strict';"],
			});

			const output = generator.generateString();

			expect(output.startsWith("/* eslint-disable */")).toBe(true);
			expect(output).toContain("'use strict';");
		});
	});

	describe("config merging", () => {
		it("should apply fileHeader from defaults", () => {
			const config: K6ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputClient: "client.ts",
						outputTypes: "types.ts",
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual(["// default-header"]);
		});

		it("should allow spec to override fileHeader from defaults", () => {
			const config: K6ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputClient: "client.ts",
						outputTypes: "types.ts",
						fileHeader: ["// spec-header"],
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual(["// spec-header"]);
		});

		it("should allow spec to disable fileHeader by setting empty array", () => {
			const config: K6ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputClient: "client.ts",
						outputTypes: "types.ts",
						fileHeader: [],
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual([]);
		});

		it("should handle config without fileHeader in defaults", () => {
			const config: K6ConfigFile = {
				defaults: {
					includeDescriptions: true,
				},
				specs: [
					{
						input: "api.yaml",
						outputClient: "client.ts",
						outputTypes: "types.ts",
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toBeUndefined();
		});
	});

	describe("service output", () => {
		it("should include custom header in service output when outputService is specified", () => {
			const generator = new OpenApiK6Generator({
				input: fixtureFile,
				outputClient: "test-client.ts",
				outputTypes: "test-types.ts",
				outputService: "test-service.ts",
				fileHeader: ["// service-header"],
			});

			const serviceOutput = generator.generateServiceString();

			// Should start with custom header
			expect(serviceOutput.startsWith("// service-header")).toBe(true);

			// Should have auto-generated comment
			expect(serviceOutput).toContain("Auto-generated by");
		});
	});
});
