import { describe, expect, it } from "vitest";

import { OpenApiGenerator } from "../src/openapi-generator";
import type { ConfigFile, OpenApiGeneratorOptions } from "../src/types";
import { mergeConfigWithDefaults } from "../src/utils/config-loader";

import { TestUtils } from "./utils/test-utils";

describe("fileHeader option", () => {
	function generateOutput(options?: Partial<OpenApiGeneratorOptions>): string {
		const generator = new OpenApiGenerator({
			input: TestUtils.getCoreFixturePath("basic", "simple.yaml"),
			outputTypes: "output.ts",
			...options,
		});
		return generator.generateString();
	}

	describe("without fileHeader", () => {
		it("should not include custom header when not specified", () => {
			const output = generateOutput();

			// Should start with auto-generated comment
			expect(output.startsWith("// Auto-generated by @cerios/openapi-to-zod")).toBe(true);
		});

		it("should not include custom header when empty array", () => {
			const output = generateOutput({ fileHeader: [] });

			// Should start with auto-generated comment
			expect(output.startsWith("// Auto-generated by @cerios/openapi-to-zod")).toBe(true);
		});
	});

	describe("with fileHeader", () => {
		it("should include single custom header line at very top", () => {
			const output = generateOutput({
				fileHeader: ["// oxlint-disable typescript/no-unsafe-type-assertion"],
			});

			// Should start with custom header
			expect(output.startsWith("// oxlint-disable typescript/no-unsafe-type-assertion")).toBe(true);

			// Should still have auto-generated comment after
			expect(output).toContain("// Auto-generated by @cerios/openapi-to-zod");
		});

		it("should include multiple custom header lines at very top", () => {
			const output = generateOutput({
				fileHeader: [
					"// oxlint-disable typescript/no-unsafe-type-assertion",
					"// oxlint-disable typescript/no-unsafe-assignment",
					"// oxlint-disable typescript/no-unsafe-member-access",
				],
			});

			const lines = output.split("\n");

			// First three lines should be our custom headers
			expect(lines[0]).toBe("// oxlint-disable typescript/no-unsafe-type-assertion");
			expect(lines[1]).toBe("// oxlint-disable typescript/no-unsafe-assignment");
			expect(lines[2]).toBe("// oxlint-disable typescript/no-unsafe-member-access");

			// Should have blank line after custom headers
			expect(lines[3]).toBe("");

			// Should still have auto-generated comment
			expect(output).toContain("// Auto-generated by @cerios/openapi-to-zod");
		});

		it("should preserve non-comment strings in fileHeader", () => {
			const output = generateOutput({
				fileHeader: ["/* eslint-disable */", "'use strict';"],
			});

			expect(output.startsWith("/* eslint-disable */")).toBe(true);
			expect(output).toContain("'use strict';");
		});

		it("should work with showStats enabled", () => {
			const output = generateOutput({
				fileHeader: ["// custom-header"],
				showStats: true,
			});

			// Custom header should be first
			expect(output.startsWith("// custom-header")).toBe(true);

			// Should have statistics
			expect(output).toContain("// Generation Statistics:");
		});

		it("should work with includeHeader disabled", () => {
			const output = generateOutput({
				fileHeader: ["// custom-header"],
				includeHeader: false,
			});

			// Custom header should be first
			expect(output.startsWith("// custom-header")).toBe(true);

			// Should NOT have auto-generated comment
			expect(output).not.toContain("// Auto-generated by");
		});
	});

	describe("fileHeader with separate schemas mode", () => {
		it("should include custom header in schemas output", () => {
			const generator = new OpenApiGenerator({
				input: TestUtils.getCoreFixturePath("basic", "simple.yaml"),
				outputTypes: "types.ts",
				outputZodSchemas: "schemas.ts",
				fileHeader: ["// schemas-file-header"],
			});

			// generateString() returns schemas when outputZodSchemas is defined
			const schemasOutput = generator.generateString();

			expect(schemasOutput.startsWith("// schemas-file-header")).toBe(true);
			expect(schemasOutput).toContain("// Auto-generated by @cerios/openapi-to-zod");
		});

		it("should include custom header in types output", () => {
			const generator = new OpenApiGenerator({
				input: TestUtils.getCoreFixturePath("basic", "simple.yaml"),
				outputTypes: "types.ts",
				outputZodSchemas: "schemas.ts",
				fileHeader: ["// types-file-header"],
			});

			const typesOutput = generator.generateTypesString();

			expect(typesOutput.startsWith("// types-file-header")).toBe(true);
			expect(typesOutput).toContain("// Auto-generated by @cerios/openapi-to-zod");
		});
	});

	describe("fileHeader in config merging", () => {
		it("should apply fileHeader from defaults", () => {
			const config: ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputTypes: "output.ts",
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual(["// default-header"]);
		});

		it("should allow spec to override fileHeader from defaults", () => {
			const config: ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputTypes: "output.ts",
						fileHeader: ["// spec-header"],
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual(["// spec-header"]);
		});

		it("should allow spec to disable fileHeader by setting empty array", () => {
			const config: ConfigFile = {
				defaults: {
					fileHeader: ["// default-header"],
				},
				specs: [
					{
						input: "api.yaml",
						outputTypes: "output.ts",
						fileHeader: [],
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toEqual([]);
		});

		it("should handle config without fileHeader in defaults", () => {
			const config: ConfigFile = {
				defaults: {
					mode: "strict",
				},
				specs: [
					{
						input: "api.yaml",
						outputTypes: "output.ts",
					},
				],
			};

			const merged = mergeConfigWithDefaults(config);

			expect(merged[0].fileHeader).toBeUndefined();
		});
	});
});
