/**
 * Header generation utilities for consistent file headers across all packages
 */

export interface FileHeaderOptions {
	/** Package name for the "Auto-generated by" line */
	packageName: string;
	/** API title from OpenAPI spec */
	apiTitle?: string;
	/** API version from OpenAPI spec */
	apiVersion?: string;
	/** Include the "Do not edit" warning */
	includeDoNotEdit?: boolean;
}

/**
 * Generate a consistent file header comment for generated files
 *
 * @param options - Header generation options
 * @returns Header string with trailing double newline for separation from content
 *
 * @example
 * generateFileHeader({ packageName: "@cerios/openapi-to-zod" })
 * // Returns:
 * // "// Auto-generated by @cerios/openapi-to-zod\n// Do not edit this file manually\n\n"
 */
export function generateFileHeader(options: FileHeaderOptions): string {
	const { packageName, apiTitle, apiVersion, includeDoNotEdit = true } = options;

	const lines: string[] = [`// Auto-generated by ${packageName}`];

	if (apiTitle) {
		lines.push(`// API: ${apiTitle}`);
	}

	if (apiVersion) {
		lines.push(`// Version: ${apiVersion}`);
	}

	if (includeDoNotEdit) {
		lines.push("// Do not edit this file manually");
	}

	return lines.join("\n") + "\n\n";
}
